# Generated by Django 3.2.25 on 2025-01-23 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('game', models.CharField(choices=[('chess', 'Chess'), ('checkers', 'Checkers'), ('tic_tac_toe', 'Tic Tac Toe')], max_length=50)),
                ('users', models.JSONField()),
                ('winner', models.CharField(max_length=255)),
                ('loser', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(max_length=18, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('record', models.TextField(default='0W-0L', max_length=100)),
                ('mmr', models.IntegerField(default='1000')),
            ],
        ),
    ]
